baseURL = 'https://shobhitsugumar.github.io/'
languageCode = 'en-us'
title = "My Blog"
theme = "PaperMod"



[params.homeInfoParams]
  title = "Bonjour!  Welcome to My Blog."
  contents = "Welcome to my BLog."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/"

[[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/"



[menu]

[[menu.main]]
  identifier = "categories"
  name = "MENU"
  url = "/categories/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "MENU2"
  url = "/tags/"
  weight = 20

[[menu.main]]
  identifier = "archive"
  name = "MENU3"
  url = "/archive/"
  weight = 30